USE essv2436_bjea;



CREATE TABLE members
(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
last_name VARCHAR(255) NOT NULL,
first_name VARCHAR(255) NOT NULL, 
cotisation TINYINT DEFAULT 0
caution TINYINT DEFAULT 0
password VARCHAR(255) NOT NULL,
jeton VARCHAR(255) NOT NULL,
isAdmin TINYINT DEFAULT 0
)
ENGINE=INNODB;

CREATE TABLE games
(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL UNIQUE,
category VARCHAR(255) NOT NULL,
brand VARCHAR(255),
players_mini TINYINT,
players_maxi TINYINT,
inStock TINYINT DEFAULT 1,
date DATE,
memberId SMALLINT UNSIGNED NOT NULL,
photo VARCHAR(255),
CONSTRAINT fk_memberId_game FOREIGN KEY (memberId) REFERENCES members(id)
ON DELETE CASCADE
ON UPDATE CASCADE
)
ENGINE=INNODB;


CREATE TABLE categories
(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,    
category VARCHAR(255) NOT NULL UNIQUE,
)
ENGINE=INNODB;



