### create a new member ###
POST http://localhost:3001/api/member/create
content-type: application/json


{
    "email": "dlphn@hotmail.fr",
    "last_name": "Moutault",
    "first_name": "Delphine",
    "cotisation":1,
    "caution":1,
    "password":"DDDddd1111"
}


### Login for a  member admin ###
POST http://localhost:3001/api/member/login
content-type: application/json

{
    "email": "del.mout@laposte.net",
    "password":"DDDddd1111"
}

### get all members ###
GET http://localhost:3001/api/member/getallmembers

### Create a new game ###
POST http://localhost:3001/api/game/create
content-type: application/json

{
    "name": "Les aventuriers du rail (Europe)",
    "category":"Plateau",
    "brand":"Days of Wonder",
    "players":"2-5",
    "inStock":1
}

### Update cotisation of a member ###
PUT http://localhost:3001/api/member/cotisation/2/0

### Update caution of a member ###
PUT http://localhost:3001/api/member/caution/2/0

### Out of stock a game ###
PUT http://localhost:3001/api/game/outofstock/1/2

### Into stock a game ###
PUT http://localhost:3001/api/game/intostock/1

### See all categories ###
GET http://localhost:3001/api/category/getallcategories

### See all games ###
GET http://localhost:3001/api/game/getallgames